version: '3'
services:
  jenkins:
    build: .
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - /home/tools/jenkins_home/:/var/jenkins_home