version: '3'
services:
  jenkins:
    build: .
    image: tools/jenkins
    container_name: jenkins
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
      DOCKER_HOST: "tcp://10.10.1.1:2376"
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - /home/tools/jenkins/jenkins_home/:/var/jenkins_home